### ISSUE TITLE
Eager macro-expansion failure: (void-variable keymap)

### ISSUE THREAD

**Issue by xianghx** [noctuid/general.el#31] opened 2016-06-21 18:30 UTC
here:
Eager macro-expansion failure: (void-variable keymap)

**Comment by noctuid** [comment] 2016-06-21 18:50
I think I know what the problem is, but can you give me steps to reproduce this and an example `general-define-key` statement?

**Comment by noctuid** [comment] 2016-06-21 18:58
Nevermind, I don't think I need any more information. The problem should be fixed.

**Closed by noctuid** 2016-06-21 18:58 UTC

**Comment by xianghx** [comment] 2016-06-21 21:58
yes, that's work.
thanks.
