### ISSUE TITLE
Override global map

### ISSUE THREAD

**Issue by avoine** [noctuid/general.el#38] opened 2016-09-30 17:02 UTC
Do you think it would be usefull to add a way to override keys in all keymaps to avoid suprises?
I found this way of doing it: https://github.com/priyadarshan/bind-key/blob/master/bind-key.el#L78
Maybe a better way would be to detect collisions and warn the user.

**Comment by noctuid** [comment] 2016-10-02 02:55
This is a duplicate of #24. There is something I wanted to try before adding this, but you can simply use that map (or your own) for now for this functionality.

**Closed by noctuid** 2016-10-02 02:55 UTC
