### ISSUE TITLE
Regression for evil keybindings together with simulate keys

### ISSUE THREAD

**Issue by terlar** [noctuid/general.el#75] opened 2017-10-31 16:57 UTC
I noticed this regression during a recent update, this has been working before. Here are the steps to reproduce:

Pre-steps:
- `M-:`
```
(setq package-archives '(
  ("gnu" . "https://elpa.gnu.org/packages/")
  ("melpa" . "https://melpa.org/packages/")))
```
- `M-x` `package-install` `general`
- `M-x` `package-install` `evil`
- `M-x` `evil-mode`

Setup key-binding:
`(general-define-key :keymaps '(normal visual) "SPC" (general-simulate-keys "C-c"))`

Press key-binding: `SPC`

Output:
```
Debugger entered--Lisp error: (invalid-function evil-save-state)
  evil-save-state(nil mode-specific-command-prefix)
  general--key-lookup(nil nil "")
  general--simulate-keys(nil "C-c" nil nil nil)
  general-simulate-C-c()
  funcall-interactively(general-simulate-C-c)
  call-interactively(general-simulate-C-c nil nil)
  command-execute(general-simulate-C-c)
```

**Comment by noctuid** [comment] 2017-10-31 17:50
Thanks for reporting. I cannot replicate this. Just to confirm, do you have the latest version of evil? I'll look into this further.

As a side note, it's not actually necessary to use `evil-save-state` here. Still, I'm not sure why it isn't working.

**Comment by terlar** [comment] 2017-10-31 17:56
Yes, I also figured it had to do with compiling. But that seems to be the default behavior?

I am testing like: `env HOME=/tmp/xyz emacs -Q` and then running the above commands.

It seems to work if I install the `evil` package before the `general` package.

As far as I can see you have been using `evil-save-state` for quite sometime, so I am not sure why I haven't run into this issue before.

I am trying to work around this in my setup where I want to have general early because of the use-package macros that I am using, but since it wants to be required/compiled after the evil package it gets kind of funky.

**Comment by noctuid** [comment] 2017-10-31 18:11
> But that seems to be the default behavior?

I use my local version of general and usually only install from MELPA if there's a problem I can't replicate.

> It seems to work if I install the evil package before the general package.

Requiring evil as a dependency would probably fix that (obviously I don't want to do that though). I'm pretty sure that the issue is that the evil macro isn't defined when general is compiled, so it's not expanded (and is assumed to be function). I could probably use `(eval-when-compile (require 'evil nil t))` to fix this, but that would still require evil to be installed before general. I'll look into some way to use `eval-after-load` instead.

**Comment by noctuid** [comment] 2017-10-31 20:47
I think the only alternative to requiring evil be installed first is to actually define the macro in general, which is now what is done. The issue is now fixed for me.

**Closed** 2017-10-31 20:46 UTC
Labels: bug
